---
- name: install apache on webservers 
  host: webserver
  become: true 

  tasks:
  - name: installing apache 
    ansible.builtin.apt:
      name: apache2
      state: present 
  - name: copy the index.html file and changing the permission
    ansible.builtin.copy:
      src: index.html
      dest: /var/www/html
      owner: root
      group: root
      mode: '0644'
      
